# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/umang/workspace/fft/fft_all_algo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/umang/workspace/fft/fft_all_algo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/umang/workspace/fft/fft_all_algo/CMakeFiles /home/umang/workspace/fft/fft_all_algo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/umang/workspace/fft/fft_all_algo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named afpwavio

# Build rule for target.
afpwavio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 afpwavio
.PHONY : afpwavio

# fast build rule for target.
afpwavio/fast:
	$(MAKE) -f CMakeFiles/afpwavio.dir/build.make CMakeFiles/afpwavio.dir/build
.PHONY : afpwavio/fast

#=============================================================================
# Target rules for targets named allgo_fft_test

# Build rule for target.
allgo_fft_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 allgo_fft_test
.PHONY : allgo_fft_test

# fast build rule for target.
allgo_fft_test/fast:
	$(MAKE) -f CMakeFiles/allgo_fft_test.dir/build.make CMakeFiles/allgo_fft_test.dir/build
.PHONY : allgo_fft_test/fast

fft_compare.o: fft_compare.c.o
.PHONY : fft_compare.o

# target to build an object file
fft_compare.c.o:
	$(MAKE) -f CMakeFiles/allgo_fft_test.dir/build.make CMakeFiles/allgo_fft_test.dir/fft_compare.c.o
.PHONY : fft_compare.c.o

fft_compare.i: fft_compare.c.i
.PHONY : fft_compare.i

# target to preprocess a source file
fft_compare.c.i:
	$(MAKE) -f CMakeFiles/allgo_fft_test.dir/build.make CMakeFiles/allgo_fft_test.dir/fft_compare.c.i
.PHONY : fft_compare.c.i

fft_compare.s: fft_compare.c.s
.PHONY : fft_compare.s

# target to generate assembly for a file
fft_compare.c.s:
	$(MAKE) -f CMakeFiles/allgo_fft_test.dir/build.make CMakeFiles/allgo_fft_test.dir/fft_compare.c.s
.PHONY : fft_compare.c.s

wav_io/wav_read.o: wav_io/wav_read.c.o
.PHONY : wav_io/wav_read.o

# target to build an object file
wav_io/wav_read.c.o:
	$(MAKE) -f CMakeFiles/afpwavio.dir/build.make CMakeFiles/afpwavio.dir/wav_io/wav_read.c.o
.PHONY : wav_io/wav_read.c.o

wav_io/wav_read.i: wav_io/wav_read.c.i
.PHONY : wav_io/wav_read.i

# target to preprocess a source file
wav_io/wav_read.c.i:
	$(MAKE) -f CMakeFiles/afpwavio.dir/build.make CMakeFiles/afpwavio.dir/wav_io/wav_read.c.i
.PHONY : wav_io/wav_read.c.i

wav_io/wav_read.s: wav_io/wav_read.c.s
.PHONY : wav_io/wav_read.s

# target to generate assembly for a file
wav_io/wav_read.c.s:
	$(MAKE) -f CMakeFiles/afpwavio.dir/build.make CMakeFiles/afpwavio.dir/wav_io/wav_read.c.s
.PHONY : wav_io/wav_read.c.s

wav_io/wav_write.o: wav_io/wav_write.c.o
.PHONY : wav_io/wav_write.o

# target to build an object file
wav_io/wav_write.c.o:
	$(MAKE) -f CMakeFiles/afpwavio.dir/build.make CMakeFiles/afpwavio.dir/wav_io/wav_write.c.o
.PHONY : wav_io/wav_write.c.o

wav_io/wav_write.i: wav_io/wav_write.c.i
.PHONY : wav_io/wav_write.i

# target to preprocess a source file
wav_io/wav_write.c.i:
	$(MAKE) -f CMakeFiles/afpwavio.dir/build.make CMakeFiles/afpwavio.dir/wav_io/wav_write.c.i
.PHONY : wav_io/wav_write.c.i

wav_io/wav_write.s: wav_io/wav_write.c.s
.PHONY : wav_io/wav_write.s

# target to generate assembly for a file
wav_io/wav_write.c.s:
	$(MAKE) -f CMakeFiles/afpwavio.dir/build.make CMakeFiles/afpwavio.dir/wav_io/wav_write.c.s
.PHONY : wav_io/wav_write.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... afpwavio"
	@echo "... allgo_fft_test"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fft_compare.o"
	@echo "... fft_compare.i"
	@echo "... fft_compare.s"
	@echo "... wav_io/wav_read.o"
	@echo "... wav_io/wav_read.i"
	@echo "... wav_io/wav_read.s"
	@echo "... wav_io/wav_write.o"
	@echo "... wav_io/wav_write.i"
	@echo "... wav_io/wav_write.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

